name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          # 基本パッケージを先にインストール
          pip install streamlit==1.28.0
          pip install pillow==9.0.0
          pip install numpy==1.26.4
          pip install transformers==4.40.0
          pip install accelerate scipy psutil
          # PyTorchを最後にCPU版でインストール
          pip install torch==2.2.2 torchvision==0.17.2 --index-url https://download.pytorch.org/whl/cpu

      - name: Create deployment package
        run: |
          mkdir deployment
          cp -r . deployment/
          rm -rf deployment/venv
          rm -rf deployment/.git
          rm -rf deployment/.github
          rm -rf deployment/model_cache
          cd deployment && zip -r ../deployment.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'AI-PoC-2025'  # 実際のApp Service名に変更してください
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: deployment.zip
